Nop.Plugin.Payments.Sadad/Controllers/PaymentSadadController.cs
using Ir.Shaparak.Sadad;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Orders;
using Nop.Plugin.Payments.Sadad.Factories;
using Nop.Plugin.Payments.Sadad.Models;
using Nop.Plugin.Payments.Sadad.Services;
using Nop.Services.Common;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Payments;
using Nop.Services.Security;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;
using System;

namespace Nop.Plugin.Payments.Sadad.Controllers
{
    public class PaymentSadadController : BasePaymentController
    {
        #region Fields

        private readonly IWorkContext _workContext;
        private readonly ISettingService _settingService;
        private readonly IPaymentService _paymentService;
        private readonly IOrderService _orderService;
        private readonly IOrderProcessingService _orderProcessingService;
        private readonly IPermissionService _permissionService;
        private readonly IGenericAttributeService _genericAttributeService;
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IStoreContext _storeContext;
        private readonly ILogger _logger;
        private readonly IWebHelper _webHelper;
        private readonly IDataProtector _dataProtector;
        private readonly ISadadGatewayPaymentService _sadadGatewayPaymentService;
        private readonly ISadadGatewayPaymentModelFactory _sadadGatewayPaymentModelFactory;
        private readonly ShoppingCartSettings _shoppingCartSettings;
        private readonly MerchantUtilitySoapClient _merchant;

        #endregion

        #region Ctor

        public PaymentSadadController(IWorkContext workContext,
            ISettingService settingService,
            IPaymentService paymentService,
            IOrderService orderService,
            IOrderProcessingService orderProcessingService,
            IPermissionService permissionService,
            IGenericAttributeService genericAttributeService,
            ILocalizationService localizationService,
            INotificationService notificationService,
            IStoreContext storeContext,
            ILogger logger,
            IWebHelper webHelper,
            IDataProtectionProvider dataProtectionProvider,
            ISadadGatewayPaymentService sadadGatewayPaymentService,
            ISadadGatewayPaymentModelFactory sadadGatewayPaymentModelFactory,
            ShoppingCartSettings shoppingCartSettings)
        {
            _workContext = workContext;
            _settingService = settingService;
            _paymentService = paymentService;
            _orderService = orderService;
            _orderProcessingService = orderProcessingService;
            _permissionService = permissionService;
            _genericAttributeService = genericAttributeService;
            _localizationService = localizationService;
            _notificationService = notificationService;
            _storeContext = storeContext;
            _logger = logger;
            _webHelper = webHelper;
            _dataProtector = dataProtectionProvider.CreateProtector(NopSmartDefaults.SecretDataProvider);
            _sadadGatewayPaymentService = sadadGatewayPaymentService;
            _sadadGatewayPaymentModelFactory = sadadGatewayPaymentModelFactory;
            _shoppingCartSettings = shoppingCartSettings;
            _merchant = new MerchantUtilitySoapClient(MerchantUtilitySoapClient.EndpointConfiguration.MerchantUtilitySoap);
        }

        #endregion

        #region Utilities

        private bool CheckRequestIsSuccessful(string appstatus, int statusCode)
        {
            return (appstatus == "COMMIT" && statusCode == 0);
        }

        #endregion

        #region Methods

        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public IActionResult Configure()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            //load settings for a chosen store scope
            var storeScope = _storeContext.ActiveStoreScopeConfiguration;
            var sadadPaymentSettings = _settingService.LoadSetting<SadadPaymentSettings>(storeScope);

            var model = new ConfigurationModel
            {
                MerchantId = sadadPaymentSettings.MerchantId,
                TerminalId = sadadPaymentSettings.TerminalId,
                TransacionKey = sadadPaymentSettings.TransacionKey,
                CurrencyIsToman = sadadPaymentSettings.CurrencyIsToman,
                AdditionalFee = sadadPaymentSettings.AdditionalFee,
                AdditionalFeePercentage = sadadPaymentSettings.AdditionalFeePercentage,
                ActiveStoreScopeConfiguration = storeScope
            };
            if (storeScope > 0)
            {
                model.MerchantId_OverrideForStore = _settingService.SettingExists(sadadPaymentSettings, x => x.MerchantId, storeScope);
                model.TerminalId_OverrideForStore = _settingService.SettingExists(sadadPaymentSettings, x => x.TerminalId, storeScope);
                model.TransacionKey_OverrideForStore = _settingService.SettingExists(sadadPaymentSettings, x => x.TransacionKey, storeScope);
                model.CurrencyIsToman_OverrideForStore = _settingService.SettingExists(sadadPaymentSettings, x => x.CurrencyIsToman, storeScope);
                model.AdditionalFee_OverrideForStore = _settingService.SettingExists(sadadPaymentSettings, x => x.AdditionalFee, storeScope);
                model.AdditionalFeePercentage_OverrideForStore = _settingService.SettingExists(sadadPaymentSettings, x => x.AdditionalFeePercentage, storeScope);
            }

            return View("~/Plugins/Payments.Sadad/Views/Configure.cshtml", model);
        }

        [HttpPost]
        [AuthorizeAdmin]
        [AdminAntiForgery]
        [Area(AreaNames.Admin)]
        public IActionResult Configure(ConfigurationModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return Configure();

            //load settings for a chosen store scope
            var storeScope = _storeContext.ActiveStoreScopeConfiguration;
            var sadadPaymentSettings = _settingService.LoadSetting<SadadPaymentSettings>(storeScope);

            //save settings
            sadadPaymentSettings.MerchantId = model.MerchantId;
            sadadPaymentSettings.TerminalId = model.TerminalId;
            sadadPaymentSettings.TransacionKey = model.TransacionKey;
            sadadPaymentSettings.CurrencyIsToman = model.CurrencyIsToman;
            sadadPaymentSettings.AdditionalFee = model.AdditionalFee;
            sadadPaymentSettings.AdditionalFeePercentage = model.AdditionalFeePercentage;

            /* We do not clear cache after each setting update.
             * This behavior can increase performance because cached settings will not be cleared 
             * and loaded from database after each update */
            _settingService.SaveSettingOverridablePerStore(sadadPaymentSettings, x => x.MerchantId, model.MerchantId_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(sadadPaymentSettings, x => x.TerminalId, model.TerminalId_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(sadadPaymentSettings, x => x.TransacionKey, model.TransacionKey_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(sadadPaymentSettings, x => x.CurrencyIsToman, model.CurrencyIsToman_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(sadadPaymentSettings, x => x.AdditionalFee, model.AdditionalFee_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(sadadPaymentSettings, x => x.AdditionalFeePercentage, model.AdditionalFeePercentage_OverrideForStore, storeScope, false);

            //now clear settings cache
            _settingService.ClearCache();

            _notificationService.SuccessNotification(_localizationService.GetResource("Admin.Plugins.Saved"));

            return Configure();
        }

        [AuthorizeAdmin]
        [AdminAntiForgery]
        [Area(AreaNames.Admin)]
        public virtual IActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            //prepare model
            var model = _sadadGatewayPaymentModelFactory.PrepareGatewayPaymentSearchModel(new SadadGatewayPaymentSearchModel());
            return View("~/Plugins/Payments.Sadad/Views/List.cshtml", model);
        }

        [HttpPost]
        [AuthorizeAdmin]
        [AdminAntiForgery]
        [Area(AreaNames.Admin)]
        public virtual IActionResult PaymentList(SadadGatewayPaymentSearchModel searchModel)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedDataTablesJson();

            //prepare model
            var model = _sadadGatewayPaymentModelFactory.PrepareGatewayPaymentListModel(searchModel);

            return Json(model);
        }

        [HttpGet]
        public IActionResult Verify(string id)
        {
            if (string.IsNullOrEmpty(id))
            {

Nop.Plugin.Payments.Sadad/Views/Configure.cshtml
@model Nop.Plugin.Payments.Sadad.Models.ConfigurationModel
@inject Nop.Core.IWebHelper webHelper
@{
    Layout = "_ConfigurePlugin";
}

@await Component.InvokeAsync("StoreScopeConfiguration")

<form asp-controller="PaymentSadad" asp-action="Configure" method="post">
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="CurrencyIsToman_OverrideForStore" asp-input="CurrencyIsToman" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="CurrencyIsToman" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="CurrencyIsToman" />
                        <span asp-validation-for="CurrencyIsToman"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="MerchantId_OverrideForStore" asp-input="MerchantId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="MerchantId" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="MerchantId" />
                        <span asp-validation-for="MerchantId"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="TerminalId_OverrideForStore" asp-input="TerminalId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="TerminalId" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="TerminalId" />
                        <span asp-validation-for="TerminalId"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="TransacionKey_OverrideForStore" asp-input="TransacionKey" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="TransacionKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="TransacionKey" />
                        <span asp-validation-for="TransacionKey"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="AdditionalFee_OverrideForStore" asp-input="AdditionalFee" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="AdditionalFee" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AdditionalFee" />
                        <span asp-validation-for="AdditionalFee"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="AdditionalFeePercentage_OverrideForStore" asp-input="AdditionalFeePercentage" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="AdditionalFeePercentage" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AdditionalFeePercentage" />
                        <span asp-validation-for="AdditionalFeePercentage"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6 col-md-offset-3">
                        <input type="submit" name="save" class="btn bg-primary" value="@T("Admin.Common.Save")" />
                    </div>
                    <div class="col-md-3 text-right">
                        <a asp-action="List" class="btn bg-primary">
                            <i class="fa fa-list"></i>
                            @T("Plugins.Payments.Sadad.PaymentList")
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Nop.Plugin.Payments.Sadad/Views/List.cshtml
@using Nop.Web.Framework.Models.DataTables
@using Nop.Plugin.Payments.Sadad.Models

@using Nop.Core.Domain.Catalog;
@{
    Layout = "_ConfigurePlugin";
}

<form asp-controller="PaymentSadad" asp-action="PaymentList" method="post">
    <div class="content">
        <div class="form-horizontal">
            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-body">
                        @await Html.PartialAsync("Table", new DataTablesModel
                   {
                       Name = "payments-grid",
                       UrlRead = new DataUrl("PaymentList", "PaymentSadad", null),
                       Length = Model.PageSize,
                       LengthMenu = Model.AvailablePageSizes,
                       ColumnCollection = new List<ColumnProperty>
                            {
                                new ColumnProperty(nameof(SadadGatewayPaymentModel.Id))
                                {
                                    Title = T("Plugins.Payments.Sadad.Fields.Id").Text,
                                    Width = "50"
                                },
                                new ColumnProperty(nameof(SadadGatewayPaymentModel.OrderId))
                                {
                                    Title = T("Plugins.Payments.Sadad.Fields.OrderId").Text,
                                    Width = "50"
                                },
                                new ColumnProperty(nameof(SadadGatewayPaymentModel.Amount))
                                {
                                    Title = T("Plugins.Payments.Sadad.Fields.Amount").Text,
                                    Width = "120"
                                },
                                new ColumnProperty(nameof(SadadGatewayPaymentModel.ClientIPAddress))
                                {
                                    Title = T("Plugins.Payments.Sadad.Fields.ClientIPAddress").Text,
                                    Width = "120"
                                },
                                new ColumnProperty(nameof(SadadGatewayPaymentModel.CreatedOn))
                                {
                                    Title = T("Plugins.Payments.Sadad.Fields.CreatedOn").Text,
                                    Width = "150",
                                    Render = new RenderDate()
                                },
                                new ColumnProperty(nameof(SadadGatewayPaymentModel.RequestedKeyOn))
                                {
                                    Title = T("Plugins.Payments.Sadad.Fields.RequestedKeyOn").Text,
                                    Width = "150",
                                    Render = new RenderDate()
                                },
                                new ColumnProperty(nameof(SadadGatewayPaymentModel.ReturnedFromBankSiteOn))
                                {
                                    Title = T("Plugins.Payments.Sadad.Fields.ReturnedFromBankSiteOn").Text,
                                    Width = "150",
                                    Render = new RenderDate()
                                },
                                new ColumnProperty(nameof(SadadGatewayPaymentModel.PaymentVerificationOn))
                                {
                                    Title = T("Plugins.Payments.Sadad.Fields.PaymentVerificationOn").Text,
                                    Width = "150",
                                    Render = new RenderDate()
                                },
                                new ColumnProperty(nameof(SadadGatewayPaymentModel.PaymentSucceed))
                                {
                                    Title = T("Plugins.Payments.Sadad.Fields.PaymentSucceed").Text,
                                    Width = "100",
                                    ClassName = NopColumnClassDefaults.CenterAll,
                                    Render = new RenderBoolean()
                                }
                            }
                   })

                    </div>
                </div>
            </div>
        </div>
    </div>

</form>

Nop.Plugin.Payments.Sadad/Views/PaymentInfo.cshtml
@{
    Layout = "";
}
<table width="100%" cellpadding="0" cellspacing="0">
    <tr>
        <td>
            <p><b>@T("Plugins.Payments.Sadad.Fields.RedirectionTip")</b></p>
        </td>
    </tr>
</table>

Nop.Plugin.Payments.Sadad/Views/RedirectToBank.cshtml
@{
    Layout = "";
}
<script language="javascript" type="text/javascript">
    function postSadadData(CardAcqID, AmountTrans, ORDERID, TerminalID, TimeStamp, FP, RedirectURL, MerchantAdditionalData, CustomerEmailAddress) {
        var form = document.createElement("form");
        form.setAttribute("method", "POST");
        form.setAttribute("action", "https://sadad.shaparak.ir/Purchase");
        form.setAttribute("target", "_self");
        //
        var hf1 = document.createElement("input");
        hf1.setAttribute("name", "CardAcqID");
        hf1.setAttribute("value", CardAcqID);
        form.appendChild(hf1);
        //
        var hf2 = document.createElement("input");
        hf2.setAttribute("name", "AmountTrans");
        hf2.setAttribute("value", AmountTrans);
        form.appendChild(hf2);
        //ORDERID
        var hf3 = document.createElement("input");
        hf3.setAttribute("name", "ORDERID");
        hf3.setAttribute("value", ORDERID);
        form.appendChild(hf3);
        //TerminalID
        var hf4 = document.createElement("input");
        hf4.setAttribute("name", "TerminalID");
        hf4.setAttribute("value", TerminalID);
        form.appendChild(hf4);
        //TimeStamp
        var hf5 = document.createElement("input");
        hf5.setAttribute("name", "TimeStamp");
        hf5.setAttribute("value", TimeStamp);
        form.appendChild(hf5);
        //FP
        var hf5 = document.createElement("input");
        hf5.setAttribute("name", "FP");
        hf5.setAttribute("value", FP);
        form.appendChild(hf5);
        //RedirectURL
        var hf6 = document.createElement("input");
        hf6.setAttribute("name", "RedirectURL");
        hf6.setAttribute("value", RedirectURL);
        form.appendChild(hf6);
        //MerchantAdditionalData
        var hf7 = document.createElement("input");
        hf7.setAttribute("name", "MerchantAdditionalData");
        hf7.setAttribute("value", MerchantAdditionalData);
        form.appendChild(hf7);
        //CustomerEmailAddress
        var hf8 = document.createElement("input");
        hf8.setAttribute("name", "CustomerEmailAddress");
        hf8.setAttribute("value", CustomerEmailAddress);
        form.appendChild(hf8);

        document.body.appendChild(form);
        form.submit();
        document.body.removeChild(form);
    }
</script>

<div class="alter alter-primary text-center">
    @Html.Raw(ViewBag.PaymentMessage)
</div>

Nop.Plugin.Payments.Sadad/Views/Verify.cshtml
@{
    Layout = "_ColumnsOne";

    //title
    Html.AddTitleParts(T("PageTitle.Checkout").Text);
    //page class
    Html.AppendPageCssClassParts("html-checkout-page");
    Html.AppendPageCssClassParts("html-order-completed-page");
}
<div class="page checkout-page order-completed-page">
    <div class="page-body checkout-data">
        <div class="section order-completed alert alert-warning text-center buttons">
            <div class="details">
                <div class="order-number">
                    <strong>@ViewBag.PaymentMessage</strong>
                </div>
            </div>
            @if (ViewBag.RePayId != null)
            {
                @*<form asp-route="OrderDetails" asp-route-orderId="@ViewBag.RePayId" method="post">
                        <input type="submit" name="repost-payment" value="@T("Order.RetryPayment")" class="button-1 btn btn-primary" />
                        <br />
                        <p class="hint">
                            <em>@T("Order.RetryPayment.Hint")</em>
                        </p>
                    </form>*@
                <a href="@Url.RouteUrl("OrderDetails", new { orderID = ViewBag.RePayId })" class="button-1 btn btn-primary">@T("Checkout.PlacedOrderDetails")</a>
            }
        </div>
    </div>
</div>